In [301]:
import numpy as np
import pandas as pd

In [302]:
dataset = pd.read_csv("50_Startups.csv")

In [303]:
dataset

R&D Spend  Administration  Marketing Spend       State     Profit
0   165349.20       136897.80        471784.10    New York  192261.83
1   162597.70       151377.59        443898.53  California  191792.06
2   153441.51       101145.55        407934.54     Florida  191050.39
3   144372.41       118671.85        383199.62    New York  182901.99
4   142107.34        91391.77        366168.42     Florida  166187.94
5   131876.90        99814.71        362861.36    New York  156991.12
6   134615.46       147198.87              NaN  California  156122.51
7   130298.13       145530.06        323876.68     Florida  155752.60
8   120542.52       148718.95        311613.29    New York  152211.77
9   123334.88       108679.17        304981.62  California  149759.96
10  101913.08             NaN        229160.95     Florida  146121.95
11  100671.96        91790.61        249744.55  California  144259.40
12   93863.75       127320.38        249839.44     Florida  141585.52
13   91992.39       135495.07        252664.93  California  134307.35
14  119943.24       156547.42        256512.92     Florida  132602.65
15  114523.61       122616.84        261776.23    New York  129917.04
16   78013.11       121597.55        264346.06  California  126992.93
17   94657.16       145077.58        282574.31    New York  125370.37
18   91749.16       114175.79        294919.57     Florida  124266.90
19   86419.70       153514.11             0.00    New York  122776.86
20   76253.86       113867.30        298664.47  California  118474.03
21   78389.47       153773.43        299737.29    New York  111313.02
22   73994.56       122782.75        303319.26     Florida  110352.25
23   67532.53       105751.03        304768.73     Florida  108733.99
24   77044.01        99281.34        140574.81    New York  108552.04
25   64664.71       139553.16        137962.62  California  107404.34
26   75328.87       144135.98        134050.07     Florida  105733.54
27   72107.60       127864.55        353183.81    New York  105008.31
28   66051.52       182645.56        118148.20     Florida  103282.38
29   65605.48       153032.06        107138.38    New York  101004.64
30   61994.48       115641.28         91131.24     Florida   99937.59
31   61136.38       152701.92         88218.23    New York   97483.56
32   63408.86       129219.61         46085.25  California   97427.84
33   55493.95       103057.49        214634.81     Florida   96778.92
34   46426.07       157693.92        210797.67  California   96712.80
35   46014.02        85047.44        205517.64    New York   96479.51
36   28663.76       127056.21        201126.82     Florida   90708.19
37   44069.95        51283.14        197029.42  California   89949.14
38   20229.59        65947.93        185265.10    New York   81229.06
39   38558.51        82982.09        174999.30  California   81005.76
40   28754.33       118546.05        172795.67  California   78239.91
41   27892.92        84710.77        164470.71     Florida   77798.83
42   23640.93        96189.63        148001.11  California   71498.49
43   15505.73       127382.30         35534.17    New York   69758.98
44   22177.74       154806.14         28334.72  California   65200.33
45    1000.23       124153.04          1903.93    New York   64926.08
46    1315.46       115816.21        297114.46     Florida   49490.75
47       0.00       135426.92             0.00  California   42559.73
48     542.05        51743.15             0.00    New York   35673.41
49       0.00       116983.80         45173.06  California   14681.40

In [304]:
dataset.isnull().any()

R&D Spend          False
Administration      True
Marketing Spend     True
State              False
Profit             False
dtype: bool

In [305]:
dataset.isnull().sum()

R&D Spend          0
Administration     1
Marketing Spend    1
State              0
Profit             0
dtype: int64

In [306]:
dataset["Administration"].mean()

121564.03816326526

In [307]:
dataset["Marketing Spend"].mean()

212725.26673469393

In [308]:
dataset["Administration"].fillna(dataset["Administration"].mean(),inplace = True)
dataset["Marketing Spend"].fillna(dataset["Marketing Spend"].mean(),inplace = True)

In [309]:
dataset

R&D Spend  Administration  Marketing Spend       State     Profit
0   165349.20   136897.800000    471784.100000    New York  192261.83
1   162597.70   151377.590000    443898.530000  California  191792.06
2   153441.51   101145.550000    407934.540000     Florida  191050.39
3   144372.41   118671.850000    383199.620000    New York  182901.99
4   142107.34    91391.770000    366168.420000     Florida  166187.94
5   131876.90    99814.710000    362861.360000    New York  156991.12
6   134615.46   147198.870000    212725.266735  California  156122.51
7   130298.13   145530.060000    323876.680000     Florida  155752.60
8   120542.52   148718.950000    311613.290000    New York  152211.77
9   123334.88   108679.170000    304981.620000  California  149759.96
10  101913.08   121564.038163    229160.950000     Florida  146121.95
11  100671.96    91790.610000    249744.550000  California  144259.40
12   93863.75   127320.380000    249839.440000     Florida  141585.52
13   91992.39   135495.070000    252664.930000  California  134307.35
14  119943.24   156547.420000    256512.920000     Florida  132602.65
15  114523.61   122616.840000    261776.230000    New York  129917.04
16   78013.11   121597.550000    264346.060000  California  126992.93
17   94657.16   145077.580000    282574.310000    New York  125370.37
18   91749.16   114175.790000    294919.570000     Florida  124266.90
19   86419.70   153514.110000         0.000000    New York  122776.86
20   76253.86   113867.300000    298664.470000  California  118474.03
21   78389.47   153773.430000    299737.290000    New York  111313.02
22   73994.56   122782.750000    303319.260000     Florida  110352.25
23   67532.53   105751.030000    304768.730000     Florida  108733.99
24   77044.01    99281.340000    140574.810000    New York  108552.04
25   64664.71   139553.160000    137962.620000  California  107404.34
26   75328.87   144135.980000    134050.070000     Florida  105733.54
27   72107.60   127864.550000    353183.810000    New York  105008.31
28   66051.52   182645.560000    118148.200000     Florida  103282.38
29   65605.48   153032.060000    107138.380000    New York  101004.64
30   61994.48   115641.280000     91131.240000     Florida   99937.59
31   61136.38   152701.920000     88218.230000    New York   97483.56
32   63408.86   129219.610000     46085.250000  California   97427.84
33   55493.95   103057.490000    214634.810000     Florida   96778.92
34   46426.07   157693.920000    210797.670000  California   96712.80
35   46014.02    85047.440000    205517.640000    New York   96479.51
36   28663.76   127056.210000    201126.820000     Florida   90708.19
37   44069.95    51283.140000    197029.420000  California   89949.14
38   20229.59    65947.930000    185265.100000    New York   81229.06
39   38558.51    82982.090000    174999.300000  California   81005.76
40   28754.33   118546.050000    172795.670000  California   78239.91
41   27892.92    84710.770000    164470.710000     Florida   77798.83
42   23640.93    96189.630000    148001.110000  California   71498.49
43   15505.73   127382.300000     35534.170000    New York   69758.98
44   22177.74   154806.140000     28334.720000  California   65200.33
45    1000.23   124153.040000      1903.930000    New York   64926.08
46    1315.46   115816.210000    297114.460000     Florida   49490.75
47       0.00   135426.920000         0.000000  California   42559.73
48     542.05    51743.150000         0.000000    New York   35673.41
49       0.00   116983.800000     45173.060000  California   14681.40

In [310]:
dataset.isnull().sum()

R&D Spend          0
Administration     0
Marketing Spend    0
State              0
Profit             0
dtype: int64

In [311]:
x = dataset.iloc[:,:4]
y = dataset.iloc[:,4]

In [312]:
x

R&D Spend  Administration  Marketing Spend       State
0   165349.20   136897.800000    471784.100000    New York
1   162597.70   151377.590000    443898.530000  California
2   153441.51   101145.550000    407934.540000     Florida
3   144372.41   118671.850000    383199.620000    New York
4   142107.34    91391.770000    366168.420000     Florida
5   131876.90    99814.710000    362861.360000    New York
6   134615.46   147198.870000    212725.266735  California
7   130298.13   145530.060000    323876.680000     Florida
8   120542.52   148718.950000    311613.290000    New York
9   123334.88   108679.170000    304981.620000  California
10  101913.08   121564.038163    229160.950000     Florida
11  100671.96    91790.610000    249744.550000  California
12   93863.75   127320.380000    249839.440000     Florida
13   91992.39   135495.070000    252664.930000  California
14  119943.24   156547.420000    256512.920000     Florida
15  114523.61   122616.840000    261776.230000    New York
16   78013.11   121597.550000    264346.060000  California
17   94657.16   145077.580000    282574.310000    New York
18   91749.16   114175.790000    294919.570000     Florida
19   86419.70   153514.110000         0.000000    New York
20   76253.86   113867.300000    298664.470000  California
21   78389.47   153773.430000    299737.290000    New York
22   73994.56   122782.750000    303319.260000     Florida
23   67532.53   105751.030000    304768.730000     Florida
24   77044.01    99281.340000    140574.810000    New York
25   64664.71   139553.160000    137962.620000  California
26   75328.87   144135.980000    134050.070000     Florida
27   72107.60   127864.550000    353183.810000    New York
28   66051.52   182645.560000    118148.200000     Florida
29   65605.48   153032.060000    107138.380000    New York
30   61994.48   115641.280000     91131.240000     Florida
31   61136.38   152701.920000     88218.230000    New York
32   63408.86   129219.610000     46085.250000  California
33   55493.95   103057.490000    214634.810000     Florida
34   46426.07   157693.920000    210797.670000  California
35   46014.02    85047.440000    205517.640000    New York
36   28663.76   127056.210000    201126.820000     Florida
37   44069.95    51283.140000    197029.420000  California
38   20229.59    65947.930000    185265.100000    New York
39   38558.51    82982.090000    174999.300000  California
40   28754.33   118546.050000    172795.670000  California
41   27892.92    84710.770000    164470.710000     Florida
42   23640.93    96189.630000    148001.110000  California
43   15505.73   127382.300000     35534.170000    New York
44   22177.74   154806.140000     28334.720000  California
45    1000.23   124153.040000      1903.930000    New York
46    1315.46   115816.210000    297114.460000     Florida
47       0.00   135426.920000         0.000000  California
48     542.05    51743.150000         0.000000    New York
49       0.00   116983.800000     45173.060000  California

In [313]:
y

0     192261.83
1     191792.06
2     191050.39
3     182901.99
4     166187.94
5     156991.12
6     156122.51
7     155752.60
8     152211.77
9     149759.96
10    146121.95
11    144259.40
12    141585.52
13    134307.35
14    132602.65
15    129917.04
16    126992.93
17    125370.37
18    124266.90
19    122776.86
20    118474.03
21    111313.02
22    110352.25
23    108733.99
24    108552.04
25    107404.34
26    105733.54
27    105008.31
28    103282.38
29    101004.64
30     99937.59
31     97483.56
32     97427.84
33     96778.92
34     96712.80
35     96479.51
36     90708.19
37     89949.14
38     81229.06
39     81005.76
40     78239.91
41     77798.83
42     71498.49
43     69758.98
44     65200.33
45     64926.08
46     49490.75
47     42559.73
48     35673.41
49     14681.40
Name: Profit, dtype: float64

In [314]:
dataset["State"].unique()

array(['New York', 'California', 'Florida'], dtype=object)

In [315]:
x.shape

(50, 4)

In [316]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

In [317]:
ct = ColumnTransformer([("one",OneHotEncoder(),[3])],remainder="passthrough")
x = ct.fit_transform(x)

In [318]:
x.shape

(50, 6)

In [319]:
x[0] # New York

array([0.000000e+00, 0.000000e+00, 1.000000e+00, 1.653492e+05,
       1.368978e+05, 4.717841e+05])

In [320]:
x[2] #Florida

array([0.0000000e+00, 1.0000000e+00, 0.0000000e+00, 1.5344151e+05,
       1.0114555e+05, 4.0793454e+05])

In [321]:
x[1] #California

array([1.0000000e+00, 0.0000000e+00, 0.0000000e+00, 1.6259770e+05,
       1.5137759e+05, 4.4389853e+05])

In [322]:
y

0     192261.83
1     191792.06
2     191050.39
3     182901.99
4     166187.94
5     156991.12
6     156122.51
7     155752.60
8     152211.77
9     149759.96
10    146121.95
11    144259.40
12    141585.52
13    134307.35
14    132602.65
15    129917.04
16    126992.93
17    125370.37
18    124266.90
19    122776.86
20    118474.03
21    111313.02
22    110352.25
23    108733.99
24    108552.04
25    107404.34
26    105733.54
27    105008.31
28    103282.38
29    101004.64
30     99937.59
31     97483.56
32     97427.84
33     96778.92
34     96712.80
35     96479.51
36     90708.19
37     89949.14
38     81229.06
39     81005.76
40     78239.91
41     77798.83
42     71498.49
43     69758.98
44     65200.33
45     64926.08
46     49490.75
47     42559.73
48     35673.41
49     14681.40
Name: Profit, dtype: float64

In [323]:
y[2]

191050.39

In [324]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.2,random_state = 1)

In [325]:
x_train.shape

(40, 6)

In [326]:
x_train

array([[1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 6.34088600e+04,
        1.29219610e+05, 4.60852500e+04],
       [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 3.85585100e+04,
        8.29820900e+04, 1.74999300e+05],
       [0.00000000e+00, 0.00000000e+00, 1.00000000e+00, 7.83894700e+04,
        1.53773430e+05, 2.99737290e+05],
       [0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 2.86637600e+04,
        1.27056210e+05, 2.01126820e+05],
       [0.00000000e+00, 0.00000000e+00, 1.00000000e+00, 8.64197000e+04,
        1.53514110e+05, 0.00000000e+00],
       [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 2.36409300e+04,
        9.61896300e+04, 1.48001110e+05],
       [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        1.16983800e+05, 4.51730600e+04],
       [0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 7.53288700e+04,
        1.44135980e+05, 1.34050070e+05],
       [0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 7.39945600e+04,
        1.22782750e+05, 

In [327]:
y_train.shape

(40,)

In [328]:
y_train

32     97427.84
39     81005.76
21    111313.02
36     90708.19
19    122776.86
42     71498.49
49     14681.40
26    105733.54
22    110352.25
13    134307.35
41     77798.83
17    125370.37
45     64926.08
24    108552.04
23    108733.99
4     166187.94
33     96778.92
14    132602.65
30     99937.59
10    146121.95
28    103282.38
44     65200.33
34     96712.80
18    124266.90
20    118474.03
25    107404.34
6     156122.51
7     155752.60
47     42559.73
1     191792.06
16    126992.93
0     192261.83
15    129917.04
5     156991.12
11    144259.40
9     149759.96
8     152211.77
12    141585.52
43     69758.98
37     89949.14
Name: Profit, dtype: float64

In [329]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [330]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [331]:
regression = Sequential()

In [332]:
regression.add(Dense(units = 6 ,kernel_initializer="random_uniform",activation = "relu"))

In [333]:
regression.add(Dense(units = 12 ,kernel_initializer="random_uniform",activation = "relu"))

In [334]:
regression.add(Dense(units = 12 ,kernel_initializer="random_uniform",activation = "relu"))


In [335]:
regression.add(Dense(units = 12 ,kernel_initializer="random_uniform",activation = "relu"))

In [336]:
regression.add(Dense(units = 1 ,kernel_initializer="random_uniform",activation = "relu"))

In [337]:
regression.compile(optimizer = "adam", loss = "mean_squared_error",metrics = ["accuracy"])

In [338]:
regression.fit(x_train,y_train,epochs=500)

Epoch 1/500
2/2 [==============================] - 0s 4ms/step - loss: 14512785408.0000 - accuracy: 0.0000e+00
Epoch 2/500
2/2 [==============================] - 0s 4ms/step - loss: 14512785408.0000 - accuracy: 0.0000e+00
Epoch 3/500
2/2 [==============================] - 0s 8ms/step - loss: 14512785408.0000 - accuracy: 0.0000e+00
Epoch 4/500
2/2 [==============================] - 0s 4ms/step - loss: 14512783360.0000 - accuracy: 0.0000e+00
Epoch 5/500
2/2 [==============================] - 0s 4ms/step - loss: 14512783360.0000 - accuracy: 0.0000e+00
Epoch 6/500
2/2 [==============================] - 0s 4ms/step - loss: 14512783360.0000 - accuracy: 0.0000e+00
Epoch 7/500
2/2 [==============================] - 0s 4ms/step - loss: 14512780288.0000 - accuracy: 0.0000e+00
Epoch 8/500
2/2 [==============================] - 0s 0s/step - loss: 14512781312.0000 - accuracy: 0.0000e+00
Epoch 9/500
2/2 [==============================] - 0s 0s/step - loss: 14512781312.0000 - accuracy: 0.0000e+00
Epo

2/2 [==============================] - 0s 4ms/step - loss: 14512114688.0000 - accuracy: 0.0000e+00
Epoch 74/500
2/2 [==============================] - 0s 4ms/step - loss: 14512067584.0000 - accuracy: 0.0000e+00
Epoch 75/500
2/2 [==============================] - 0s 0s/step - loss: 14512010240.0000 - accuracy: 0.0000e+00
Epoch 76/500
2/2 [==============================] - 0s 4ms/step - loss: 14511950848.0000 - accuracy: 0.0000e+00
Epoch 77/500
2/2 [==============================] - 0s 4ms/step - loss: 14511885312.0000 - accuracy: 0.0000e+00
Epoch 78/500
2/2 [==============================] - 0s 0s/step - loss: 14511819776.0000 - accuracy: 0.0000e+00
Epoch 79/500
2/2 [==============================] - 0s 4ms/step - loss: 14511753216.0000 - accuracy: 0.0000e+00
Epoch 80/500
2/2 [==============================] - 0s 4ms/step - loss: 14511672320.0000 - accuracy: 0.0000e+00
Epoch 81/500
2/2 [==============================] - 0s 0s/step - loss: 14511593472.0000 - accuracy: 0.0000e+00
Epoch 82

2/2 [==============================] - 0s 4ms/step - loss: 14476515328.0000 - accuracy: 0.0000e+00
Epoch 147/500
2/2 [==============================] - 0s 0s/step - loss: 14475075584.0000 - accuracy: 0.0000e+00
Epoch 148/500
2/2 [==============================] - 0s 0s/step - loss: 14473630720.0000 - accuracy: 0.0000e+00
Epoch 149/500
2/2 [==============================] - 0s 4ms/step - loss: 14472036352.0000 - accuracy: 0.0000e+00
Epoch 150/500
2/2 [==============================] - 0s 4ms/step - loss: 14470463488.0000 - accuracy: 0.0000e+00
Epoch 151/500
2/2 [==============================] - 0s 0s/step - loss: 14468846592.0000 - accuracy: 0.0000e+00
Epoch 152/500
2/2 [==============================] - 0s 0s/step - loss: 14467139584.0000 - accuracy: 0.0000e+00
Epoch 153/500
2/2 [==============================] - 0s 4ms/step - loss: 14465305600.0000 - accuracy: 0.0000e+00
Epoch 154/500
2/2 [==============================] - 0s 0s/step - loss: 14463490048.0000 - accuracy: 0.0000e+00
Ep

Epoch 219/500
2/2 [==============================] - 0s 0s/step - loss: 14144309248.0000 - accuracy: 0.0000e+00
Epoch 220/500
2/2 [==============================] - 0s 4ms/step - loss: 14135705600.0000 - accuracy: 0.0000e+00
Epoch 221/500
2/2 [==============================] - 0s 0s/step - loss: 14126553088.0000 - accuracy: 0.0000e+00
Epoch 222/500
2/2 [==============================] - 0s 0s/step - loss: 14117345280.0000 - accuracy: 0.0000e+00
Epoch 223/500
2/2 [==============================] - 0s 6ms/step - loss: 14108005376.0000 - accuracy: 0.0000e+00
Epoch 224/500
2/2 [==============================] - ETA: 0s - loss: 14289816576.0000 - accuracy: 0.0000e+ - 0s 4ms/step - loss: 14098215936.0000 - accuracy: 0.0000e+00
Epoch 225/500
2/2 [==============================] - 0s 4ms/step - loss: 14088275968.0000 - accuracy: 0.0000e+00
Epoch 226/500
2/2 [==============================] - 0s 4ms/step - loss: 14078410752.0000 - accuracy: 0.0000e+00
Epoch 227/500
2/2 [========================

2/2 [==============================] - 0s 0s/step - loss: 12892227584.0000 - accuracy: 0.0000e+00
Epoch 292/500
2/2 [==============================] - 0s 0s/step - loss: 12864206848.0000 - accuracy: 0.0000e+00
Epoch 293/500
2/2 [==============================] - 0s 3ms/step - loss: 12837407744.0000 - accuracy: 0.0000e+00
Epoch 294/500
2/2 [==============================] - 0s 4ms/step - loss: 12810620928.0000 - accuracy: 0.0000e+00
Epoch 295/500
2/2 [==============================] - 0s 5ms/step - loss: 12779284480.0000 - accuracy: 0.0000e+00
Epoch 296/500
2/2 [==============================] - 0s 4ms/step - loss: 12753219584.0000 - accuracy: 0.0000e+00
Epoch 297/500
2/2 [==============================] - 0s 0s/step - loss: 12722855936.0000 - accuracy: 0.0000e+00
Epoch 298/500
2/2 [==============================] - 0s 0s/step - loss: 12692197376.0000 - accuracy: 0.0000e+00
Epoch 299/500
2/2 [==============================] - 0s 0s/step - loss: 12662929408.0000 - accuracy: 0.0000e+00
Ep

2/2 [==============================] - 0s 0s/step - loss: 9949472768.0000 - accuracy: 0.0000e+00
Epoch 364/500
2/2 [==============================] - 0s 0s/step - loss: 9895682048.0000 - accuracy: 0.0000e+00
Epoch 365/500
2/2 [==============================] - 0s 0s/step - loss: 9841813504.0000 - accuracy: 0.0000e+00
Epoch 366/500
2/2 [==============================] - 0s 983us/step - loss: 9789282304.0000 - accuracy: 0.0000e+00
Epoch 367/500
2/2 [==============================] - 0s 0s/step - loss: 9736086528.0000 - accuracy: 0.0000e+00
Epoch 368/500
2/2 [==============================] - 0s 0s/step - loss: 9677527040.0000 - accuracy: 0.0000e+00
Epoch 369/500
2/2 [==============================] - 0s 0s/step - loss: 9629062144.0000 - accuracy: 0.0000e+00
Epoch 370/500
2/2 [==============================] - 0s 0s/step - loss: 9576580096.0000 - accuracy: 0.0000e+00
Epoch 371/500
2/2 [==============================] - 0s 0s/step - loss: 9523675136.0000 - accuracy: 0.0000e+00
Epoch 372/50

2/2 [==============================] - 0s 4ms/step - loss: 5946157056.0000 - accuracy: 0.0000e+00
Epoch 436/500
2/2 [==============================] - 0s 5ms/step - loss: 5894183936.0000 - accuracy: 0.0000e+00
Epoch 437/500
2/2 [==============================] - 0s 0s/step - loss: 5840638464.0000 - accuracy: 0.0000e+00
Epoch 438/500
2/2 [==============================] - 0s 4ms/step - loss: 5788403200.0000 - accuracy: 0.0000e+00
Epoch 439/500
2/2 [==============================] - 0s 0s/step - loss: 5736527360.0000 - accuracy: 0.0000e+00
Epoch 440/500
2/2 [==============================] - 0s 0s/step - loss: 5686043648.0000 - accuracy: 0.0000e+00
Epoch 441/500
2/2 [==============================] - 0s 0s/step - loss: 5634834432.0000 - accuracy: 0.0000e+00
Epoch 442/500
2/2 [==============================] - 0s 0s/step - loss: 5583803392.0000 - accuracy: 0.0000e+00
Epoch 443/500
2/2 [==============================] - 0s 0s/step - loss: 5535394304.0000 - accuracy: 0.0000e+00
Epoch 444/50

In [339]:
ypred = regression.predict(x_test)

In [340]:
ypred

array([[102430.23 ],
       [ 24110.352],
       [ 17309.717],
       [ 12500.279],
       [154670.44 ],
       [164201.72 ],
       [  2973.951],
       [ 45174.6  ],
       [ 37131.285],
       [ 37914.344]], dtype=float32)

In [341]:
dataset

R&D Spend  Administration  Marketing Spend       State     Profit
0   165349.20   136897.800000    471784.100000    New York  192261.83
1   162597.70   151377.590000    443898.530000  California  191792.06
2   153441.51   101145.550000    407934.540000     Florida  191050.39
3   144372.41   118671.850000    383199.620000    New York  182901.99
4   142107.34    91391.770000    366168.420000     Florida  166187.94
5   131876.90    99814.710000    362861.360000    New York  156991.12
6   134615.46   147198.870000    212725.266735  California  156122.51
7   130298.13   145530.060000    323876.680000     Florida  155752.60
8   120542.52   148718.950000    311613.290000    New York  152211.77
9   123334.88   108679.170000    304981.620000  California  149759.96
10  101913.08   121564.038163    229160.950000     Florida  146121.95
11  100671.96    91790.610000    249744.550000  California  144259.40
12   93863.75   127320.380000    249839.440000     Florida  141585.52
13   91992.39   135495.070000    252664.930000  California  134307.35
14  119943.24   156547.420000    256512.920000     Florida  132602.65
15  114523.61   122616.840000    261776.230000    New York  129917.04
16   78013.11   121597.550000    264346.060000  California  126992.93
17   94657.16   145077.580000    282574.310000    New York  125370.37
18   91749.16   114175.790000    294919.570000     Florida  124266.90
19   86419.70   153514.110000         0.000000    New York  122776.86
20   76253.86   113867.300000    298664.470000  California  118474.03
21   78389.47   153773.430000    299737.290000    New York  111313.02
22   73994.56   122782.750000    303319.260000     Florida  110352.25
23   67532.53   105751.030000    304768.730000     Florida  108733.99
24   77044.01    99281.340000    140574.810000    New York  108552.04
25   64664.71   139553.160000    137962.620000  California  107404.34
26   75328.87   144135.980000    134050.070000     Florida  105733.54
27   72107.60   127864.550000    353183.810000    New York  105008.31
28   66051.52   182645.560000    118148.200000     Florida  103282.38
29   65605.48   153032.060000    107138.380000    New York  101004.64
30   61994.48   115641.280000     91131.240000     Florida   99937.59
31   61136.38   152701.920000     88218.230000    New York   97483.56
32   63408.86   129219.610000     46085.250000  California   97427.84
33   55493.95   103057.490000    214634.810000     Florida   96778.92
34   46426.07   157693.920000    210797.670000  California   96712.80
35   46014.02    85047.440000    205517.640000    New York   96479.51
36   28663.76   127056.210000    201126.820000     Florida   90708.19
37   44069.95    51283.140000    197029.420000  California   89949.14
38   20229.59    65947.930000    185265.100000    New York   81229.06
39   38558.51    82982.090000    174999.300000  California   81005.76
40   28754.33   118546.050000    172795.670000  California   78239.91
41   27892.92    84710.770000    164470.710000     Florida   77798.83
42   23640.93    96189.630000    148001.110000  California   71498.49
43   15505.73   127382.300000     35534.170000    New York   69758.98
44   22177.74   154806.140000     28334.720000  California   65200.33
45    1000.23   124153.040000      1903.930000    New York   64926.08
46    1315.46   115816.210000    297114.460000     Florida   49490.75
47       0.00   135426.920000         0.000000  California   42559.73
48     542.05    51743.150000         0.000000    New York   35673.41
49       0.00   116983.800000     45173.060000  California   14681.40

In [342]:
yp = regression.predict(sc.transform([[1,0,0,78013.11,121597.550000,264346.060000]])) #16th row

In [343]:
yp

array([[40206.43]], dtype=float32)

In [344]:
yp = regression.predict(sc.transform([[0,0,1,542.05,51743.150000,0.000000]])) #48 row

In [346]:
yp

array([[2973.951]], dtype=float32)

In [348]:
sc.transform([[0,0,1,542.05,51743.150000,0.000000]]) #48th row

array([[-0.81649658, -0.73379939,  1.73205081, -1.7740986 , -2.85105775,
        -1.7867942 ]])

In [350]:
sc.transform([[1,0,0,78013.11,121597.550000,264346.060000]]) #16th row

array([[ 1.22474487, -0.73379939, -0.57735027,  0.01615437, -0.12094516,
         0.45283518]])